### ISSUE TITLE
NullPointerException when I "Show abstract syntax"

### ISSUE THREAD

**Issue by Toxaris** [seba--/sugarj#11]
SugarJ throws a NullPointerException when I select "Show abstract syntax" from the Transform menu.

**To reproduce:** Open a file, select a small part of the file, select "Show abstract syntax".

**The exception** (as displayed in the Spoofax/IMP console):

```
java.lang.NullPointerException
    at org.strategoxt.imp.runtime.services.InputTermBuilder.tryGetProjectPath(InputTermBuilder.java:167)
    at org.strategoxt.imp.runtime.services.StrategoObserver.configureRuntime(StrategoObserver.java:802)
    at org.strategoxt.imp.runtime.services.StrategoObserver.invoke(StrategoObserver.java:674)
    at org.strategoxt.imp.runtime.services.StrategoObserver.invoke(StrategoObserver.java:658)
    at org.strategoxt.imp.runtime.services.StrategoBuilder.invokeObserver(StrategoBuilder.java:305)
    at org.strategoxt.imp.runtime.services.StrategoBuilder.execute(StrategoBuilder.java:185)
    at org.strategoxt.imp.runtime.services.StrategoBuilder.access$1(StrategoBuilder.java:170)
    at org.strategoxt.imp.runtime.services.StrategoBuilder$1.run(StrategoBuilder.java:157)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by Toxaris** [comment]
The difference between this issue and #10 seems to be what part of the file is requested for transformation: If the whole file is requested, #10 happens. If only a sub-AST is selected, #11 happens.

**Comment by seba--** [comment]
does not occur anymore.
